import json
import re
from typing import Annotated, TypedDict, List

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from langchain_core.tools import tool

from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode, tools_condition

from agent_tool.agent.tools.tools import search_suppliers, is_valid_company, extract_from_paginegialle, research_and_extract_company

from agent_tool.logger import logger
from agent_tool.config import *

LLM = ChatOllama(
    base_url=OLLAMA_BASE_URL,
    model=MODEL,
    format="json",
    temperature=0
)

tools = [
    search_suppliers, 
    is_valid_company, 
    extract_from_paginegialle, 
    research_and_extract_company
]

llm_with_tools = LLM.bind_tools(tools)


SYSTEM_PROMPT = """You are an autonomous, expert supplier search assistant. 
Your goal is to find potential suppliers based on the user's query and extract their contact information.

CRITICAL WORKFLOW RULES - YOU MUST FOLLOW THESE:
1. Search: Start by using `search_suppliers`.
2. PagineGialle Handling: If ANY URL contains "paginegialle.it", you MUST use the `extract_from_paginegialle` tool on that URL immediately.
3. Validation: For standard URLs, use `is_valid_company`.
4. Deduplication: Keep track of websites you have already processed in the chat history. Skip duplicates.
5. Extraction: For every valid company URL, use `research_and_extract_company`.

NO PREMATURE STOPPING:
You MUST process every single URL you find in the search results. 
Do not stop until you have evaluated every URL and extracted data from all the valid ones.
Once you have finished processing ALL URLs, and ONLY then, formulate your final response presenting all extracted companies as a single structured JSON array.
"""

# STATE
class InputState(TypedDict):
    query: str

class OutputState(TypedDict):
    answer: str

class OverallState(InputState, OutputState):
    messages: Annotated[list, add_messages]

# NODE
def init_node(state: InputState):
    """
    Prende la query testuale passata dall'utente (o da LangSmith)
    e la converte nel formato `messages` richiesto dall'LLM.
    """
    user_query = state["query"]
    return {"messages": [HumanMessage(content=user_query)]}

def agent_node(state: OverallState):
    """
    The Agent node. It represents the "brain" of the graph where the LLM thinks
    and decides whether to call a tool or provide the final answer.
    """
    
    # Extract the conversation history from the global state.
    # This gives the LLM context about the user's query and the tool results it has already seen.
    messages = state.get("messages", [])
    
    # Prepend the System Prompt to the beginning of the message history.
    # We do this dynamically in RAM right before calling the LLM, rather than saving it 
    # to the graph's state, to prevent the prompt from duplicating at every loop iteration.
    messages_with_system = [SystemMessage(content=SYSTEM_PROMPT)] + messages
    
    response = llm_with_tools.invoke(messages_with_system)
    
    # Append the LLM's new thought/action to the existing list of messages in the state.
    state_update = {"messages": [response]}
    
    # We check if the LLM decided NOT to call any tools. If the 'tool_calls' list is empty 
    # or missing, it means the LLM has finished researching and wrote the final JSON array.
    if getattr(response, "tool_calls", None) is None or len(response.tool_calls) == 0:
        # We capture this final text and put it into the 'answer' key. 
        # This tells LangGraph to populate the OutputState and finish the process.
        state_update["answer"] = response.content
        
    return state_update

# BUILD GRAPH
graph = StateGraph(
    OverallState,
    input_schema=InputState,
    output_schema=OutputState
)    

graph.add_node("init", init_node)
graph.add_node("agent", agent_node)
graph.add_node("tools", ToolNode(tools))

graph.add_edge(START, "init")
graph.add_edge("init", "agent")
graph.add_conditional_edges("agent", tools_condition)
graph.add_edge("tools", "agent")

app = graph.compile()

def run_agent(query: str):
    logger.info(f"[AGENT START] Query: {query}")
    
    try:
        result = app.invoke({"query": query})
        
        # Check for the presence of an answer
        if "answer" not in result:
            return None, "No answer generated by the agent."
        
        raw_answer = result.get("answer", "")

        # Clean up and remove Markdown code blocks
        cleaned_text = raw_answer.strip()
        match = re.search(r'```(?:json)?(.*?)```', cleaned_text, re.DOTALL | re.IGNORECASE)
        if match:
            cleaned_text = match.group(1).strip()

        # Parse the JSON
        try:
            parsed_json = json.loads(cleaned_text)
        except json.JSONDecodeError as e:
            error_msg = f"JSON Decode Error: {str(e)}"
            logger.error(f"[AGENT PARSE ERROR] {error_msg}\nReceived string: {raw_answer}")
            return None, error_msg
            
        # Return on success
        return parsed_json, None

    except Exception as e:
        # Handle fatal errors (e.g., app.invoke fails)
        logger.error(f"[AGENT FATAL ERROR] {e}")
        return None, str(e)