# SEARXNG CONFIG
SEARXNG_URL = "http://localhost:8080"

# SEARCH LIMITS
SEARXNG_RESULTS_LIMIT = 3
PAGINEGIALLE_RESULTS_LIMIT = 2

# OLLAMA CONFIG
OLLAMA_BASE_URL = "http://localhost:11434"

# LLM MODELS
AGENT_DBMANAGER_MODEL = "gemma4:31b-cloud"
AGENT_ORCHESTRATOR_MODEL = "gemma4:31b-cloud"
AGENT_PIPELINE_MODEL = "gemma4:31b-cloud"
AGENT_TOOL_MODEL = "gemma4:31b-cloud"