import json
from langchain_core.tools import tool
from typing import Annotated, TypedDict
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, START
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode, tools_condition
from config import *
from logger import logger
from agent_orchestrator.sub_agents import run_search_agent, run_dbmanager_agent
from artifact_store import artifact_store
from main import print_event
from stats import get_stats

# System prompt defining the orchestrator's behavior with strict workflow and deduplication rules
SYSTEM_PROMPT = """
You are an Orchestrator Agent.
Your responsibility is ONLY to coordinate subagents and move data through artifacts.

You never search the web directly.
You never access the database directly.
You never transform, summarize, interpret, filter, merge, or modify data.

Your only responsibility is executing tools in the correct order.

MANDATORY WORKFLOW:

STEP 1 — SEARCH FOR SUPPLIERS

Call:

run_search_agent(USER_REQUEST)

Purpose:
- Search external sources for suppliers matching the user request.

Example user request:
"fornitori materiali edili Pisa"

Result:
SEARCH_ARTIFACT_ID

If an error is returned:
- Stop immediately
- Return the error message
- Do not execute additional tools

STEP 2 — STORE SEARCH RESULTS

Call run_dbmanager_agent with a NATURAL LANGUAGE instruction.

Example:

"Insert new supplier data from artifact SEARCH_ARTIFACT_ID"

Purpose:
- Persist newly discovered suppliers into the database.

IMPORTANT:
- Never load the artifact yourself.
- Never include JSON in the instruction.
- The dbmanager is responsible for reading the artifact.

Wait for completion.

If insertion fails:
- Stop immediately
- Return the error

STEP 3 — RETRIEVE FINAL DATA FROM DATABASE

Call run_dbmanager_agent again.

Input:
A natural language retrieval request.

Example:

"Retrieve all supplier data related to: USER_REQUEST"

Purpose:
- Retrieve the complete database view for the requested suppliers.

IMPORTANT:
- Retrieval MUST happen through dbmanager.
- The dbmanager decides how to build queries internally.

Expected result:
FINAL_ARTIFACT_ID

If retrieval fails:
- Stop immediately
- Return the error

STEP 4 — LOAD FINAL RESULT

Call:

load_artifact(FINAL_ARTIFACT_ID)

Purpose:
- Retrieve the final JSON payload.

STEP 5 — RETURN RESULT

Return ONLY the JSON content returned by load_artifact.

Do not:
- modify it
- summarize it
- explain it
- reorder fields
- filter records
- wrap it in markdown
- generate additional text

----------------------------------------------------------------------
HARD RULES
- Never process data yourself
- Never inspect artifacts unless using load_artifact
- Never pass structured payloads between agents
- Always exchange data using artifact_id
- Never generate database queries
- Never search outside run_search_agent
- Never bypass dbmanager
- Never invent supplier data
- Follow the workflow exactly
"""

@tool("load_artifact")
def load_artifact(artifact_id: str) -> str:
    """
    Load the content of an artifact from the artifact store.

    This tool is intended to be used to retrieve data
    that was previously persisted by other agents or tools.

    The tool accepts only an `artifact_id` and returns the complete artifact
    content serialized as a raw JSON string.

    This tool does not:
    - Execute business logic
    - Perform database operations
    - Modify artifact contents
    - Interpret or validate the stored data

    It only retrieves and exposes the stored payload.

    Typical usage scenarios:
    - Read supplier search results generated by the web-search subagent
    - Retrieve structured datasets returned by the database manager
    - Access intermediate results produced during multi-agent workflows
    - Load large payloads that were intentionally stored outside agent messages

    Examples:
    - Load artifact "vYtM84r9uP2E9zXyB6Hn9c"
    - Read supplier search output from artifact "aYtZ84r3uP2I9zPyB6Ln9c"

    Artifact workflow:
    1. Another tool or subagent generates structured data.
    2. The data is stored in the artifact store.
    3. An `artifact_id` is returned.
    4. This tool is used to retrieve the stored content.

    Args:
        artifact_id:
            Unique identifier of the artifact to load.

            The identifier must reference an existing artifact previously
            persisted in the artifact store.

    Returns:
        str:
            The artifact content serialized as a raw JSON string.

            Example:
            '{"suppliers": [...], "metadata": {...}}'

    Raises:
        Errors generated by artifact loading are propagated by the underlying
        artifact store implementation.
    """
    data = artifact_store.load(artifact_id)
    return json.dumps(data)

# List of available tools for the orchestrator
tools = [
    run_search_agent,
    run_dbmanager_agent,
    load_artifact
]

# Bind tools to the LLM
llm_with_tools = AGENT_ORCHESTRATOR_LLM.bind_tools(tools)


# State definitions for LangGraph
class InputState(TypedDict):
    """Input state schema - requires a query string."""
    query: str


class OutputState(TypedDict):
    """Output state schema - contains the answer."""
    answer: str


class OverallState(InputState, OutputState):
    """Combined state with messages history for the agent."""
    messages: Annotated[list, add_messages]


def init_node(state: InputState) -> OverallState:
    """
    Initialize the agent state with the user's query.
    Converts the input query into a HumanMessage for the LLM.
    """
    user_query = state["query"]
    logger.info(f"[ORCHESTRATOR - INIT NODE] Executing init node. Received query: {user_query}")
    return {"messages": [HumanMessage(content=user_query)]}


def agent_node(state: OverallState) -> OverallState:
    """
    Main agent node that processes messages and decides on tool calls.

    Invokes the LLM with the system prompt and message history,
    then returns the response for tool execution or final answer.
    """
    logger.info("[ORCHESTRATOR - AGENT NODE] Executing agent node")
    stats = get_stats()

    messages = state.get("messages", [])
    messages_with_system = [SystemMessage(content=SYSTEM_PROMPT)] + messages

    response = llm_with_tools.invoke(messages_with_system)

    # Update stats
    usage = response.usage_metadata or {}
    input_tokens = usage.get("input_tokens", 0)
    output_tokens = usage.get("output_tokens", 0)
    stats.add_request(input_tokens, output_tokens)

    state_update = {"messages": [response]}

    if getattr(response, "tool_calls", None) is None or len(response.tool_calls) == 0:
        state_update["answer"] = response.content
    else:
        for _ in response.tool_calls:
            stats.add_tool_call()

    return state_update


# Build the LangGraph state machine
graph = StateGraph(
    OverallState,
    input_schema=InputState,
    output_schema=OutputState
)

# Add nodes to the graph
graph.add_node("init", init_node)
graph.add_node("agent", agent_node)
graph.add_node("tools", ToolNode(tools))

# Define edges
graph.add_edge(START, "init")
graph.add_edge("init", "agent")
graph.add_conditional_edges("agent", tools_condition)
graph.add_edge("tools", "agent")

# Compile the graph
app = graph.compile()


def run_orchestrator(query: str) -> tuple:
    """
    Execute the orchestrator agent with a given query.

    Args:
        query: The user query to process

    Returns:
        Tuple of (answer, error) where error is None on success
    """
    logger.info(f"[ORCHESTRATOR] Starting orchestration with query: {query}")

    try:
        last_event = None
        for event in app.stream({"query": query}):
            print_event("ORCHESTRATOR", event)
            last_event = event

        if last_event is None:
            logger.error("[ORCHESTRATOR FATAL ERROR] Graph produced no events")
            return None, "Graph produced no events"

        agent_messages = last_event.get("agent", {}).get("messages", [])
        if not agent_messages:
            error_msg = last_event.get("error")
            if error_msg:
                return None, error_msg
            logger.error("[ORCHESTRATOR FATAL ERROR] No messages in last agent event")
            return None, "No final answer produced"

        messages = agent_messages[0]
        return getattr(messages, "content", None), None

    except Exception as e:
        logger.error(f"[ORCHESTRATOR FATAL ERROR] {e}")
        return None, str(e)